package nl.jjt.vorfahrtfahrradcompanion.settings.db

import androidx.room.RoomDatabaseConstructor

/** The `actual` is generated by Room's KSP processor — do not write one. */
@Suppress("KotlinNoActualForExpect")
expect object AppDatabaseConstructor : RoomDatabaseConstructor<AppDatabase> {
    override fun initialize(): AppDatabase
}
